[server]
# Increase upload limit to 10GB for large CSV imports
maxUploadSize = 10000  # 10GB in MB
maxMessageSize = 10000

[theme]
# Light Theme Configuration
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#1A1A1A"
font = "sans serif"

# Dark Theme Colors (warm tones with brown/orange accents)
# These are applied via theme_manager.py
# backgroundColor = "#1A1410"
# secondaryBackgroundColor = "#2D2416"
# textColor = "#E8D5C4"
# primaryColor = "#FF8C42"

