# Generated by Django 5.0.1 on 2025-10-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(db_index=True, max_length=255)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "company",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "industry",
                    models.CharField(blank=True, db_index=True, max_length=150),
                ),
                ("company_size", models.CharField(blank=True, max_length=50)),
                ("company_address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("employees_count", models.IntegerField(blank=True, null=True)),
                ("annual_revenue", models.IntegerField(blank=True, null=True)),
                ("total_funding", models.IntegerField(blank=True, null=True)),
                ("latest_funding_amount", models.IntegerField(blank=True, null=True)),
                ("seniority", models.CharField(blank=True, max_length=100)),
                ("departments", models.TextField(blank=True)),
                ("keywords", models.TextField(blank=True)),
                ("technologies", models.TextField(blank=True)),
                ("email_status", models.CharField(blank=True, max_length=50)),
                ("stage", models.CharField(blank=True, max_length=50)),
                ("city", models.CharField(blank=True, db_index=True, max_length=150)),
                ("state", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "country",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("company_city", models.CharField(blank=True, max_length=150)),
                ("company_state", models.CharField(blank=True, max_length=100)),
                ("company_country", models.CharField(blank=True, max_length=100)),
                ("company_phone", models.CharField(blank=True, max_length=50)),
                ("linkedin", models.URLField(blank=True)),
                ("person_linkedin_url", models.URLField(blank=True)),
                ("company_linkedin_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("facebook", models.CharField(blank=True, max_length=255)),
                ("twitter_url", models.URLField(blank=True)),
                ("twitter", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="active", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "contacts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="email_idx"),
                    models.Index(fields=["company"], name="company_idx"),
                    models.Index(fields=["industry"], name="industry_idx"),
                    models.Index(fields=["country"], name="country_idx"),
                    models.Index(fields=["city"], name="city_idx"),
                ],
            },
        ),
    ]
