# Generated by Django 4.2.25 on 2025-10-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Industry",
                "verbose_name_plural": "Industries",
                "db_table": "industries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(db_index=True, max_length=255)),
                ("last_name", models.CharField(db_index=True, max_length=255)),
                (
                    "title",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("seniority", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "departments",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                (
                    "email_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "primary_email_catch_all_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "work_direct_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("home_phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "mobile_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "corporate_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("other_phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "company",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "company_name_for_emails",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("employees", models.IntegerField(blank=True, null=True)),
                ("stage", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "total_funding",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "latest_funding",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "latest_funding_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("last_raised_at", models.DateField(blank=True, null=True)),
                (
                    "city",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("company_address", models.TextField(blank=True, null=True)),
                (
                    "company_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "company_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "company_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "company_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("technologies", models.TextField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                ("person_linkedin_url", models.URLField(blank=True, null=True)),
                ("company_linkedin_url", models.URLField(blank=True, null=True)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("contact_id", models.CharField(blank=True, max_length=100, null=True)),
                ("account_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "industry_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="contacts.industry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "db_table": "contacts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="contacts_first_n_e3c7c9_idx",
                    ),
                    models.Index(
                        fields=["company", "industry"],
                        name="contacts_company_2ab508_idx",
                    ),
                    models.Index(
                        fields=["city", "country"], name="contacts_city_803332_idx"
                    ),
                    models.Index(
                        fields=["email_status"], name="contacts_email_s_a857a6_idx"
                    ),
                    models.Index(
                        fields=["employees"], name="contacts_employe_d5970d_idx"
                    ),
                ],
            },
        ),
    ]
