# Generated by Django 5.0.1 on 2025-10-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("BOOLEAN", "Boolean"),
                            ("STRING", "String"),
                            ("INTEGER", "Integer"),
                            ("JSON", "JSON"),
                        ],
                        default="STRING",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.CreateModel(
            name="TaskCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#007bff", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-tasks",
                        help_text="Font Awesome icon class",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Task Category",
                "verbose_name_plural": "Task Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TaskTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SETUP", "Setup"),
                            ("IMPORT", "Import"),
                            ("EXPORT", "Export"),
                            ("ANALYTICS", "Analytics"),
                            ("UI_UX", "UI/UX"),
                            ("TESTING", "Testing"),
                            ("PERFORMANCE", "Performance"),
                            ("DOCUMENTATION", "Documentation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("task_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Task Tracker",
                "verbose_name_plural": "Task Trackers",
                "ordering": ["category", "order", "task_name"],
            },
        ),
    ]
