# Generated by Django 5.0.1 on 2025-10-28 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExportLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("export_count", models.IntegerField(default=0)),
                ("limit", models.IntegerField(default=100)),
                ("reset_at", models.DateTimeField(auto_now_add=True)),
                ("last_export_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "export_limits",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("contacts", "Contacts"),
                            ("analytics", "Analytics"),
                            ("quality_report", "Quality Report"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("excel", "Excel"), ("json", "JSON")],
                        default="csv",
                        max_length=20,
                    ),
                ),
                (
                    "record_count",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("filters_applied", models.JSONField(blank=True, default=dict)),
                ("filename", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "export_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "created_at"], name="user_export_idx"
                    ),
                    models.Index(fields=["export_type"], name="export_type_idx"),
                ],
            },
        ),
    ]
