# Generated by Django 5.0.1 on 2025-10-28 09:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exports", "0002_add_filters_applied"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="exportlog",
            name="user_export_idx",
        ),
        migrations.RenameField(
            model_name="exportlog",
            old_name="user_id",
            new_name="supabase_user_id",
        ),
        migrations.AddField(
            model_name="exportlog",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="file_path",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="progress_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="exportlog",
            name="export_format",
            field=models.CharField(
                choices=[
                    ("csv", "CSV"),
                    ("excel", "Excel"),
                    ("json", "JSON"),
                    ("pdf", "PDF"),
                ],
                default="csv",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exportlog",
            name="export_type",
            field=models.CharField(
                choices=[
                    ("contacts", "Contacts"),
                    ("analytics", "Analytics"),
                    ("quality_report", "Quality Report"),
                    ("bulk_export", "Bulk Export"),
                    ("selected_contacts", "Selected Contacts"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="exportlog",
            name="record_count",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddIndex(
            model_name="exportlog",
            index=models.Index(
                fields=["supabase_user_id", "created_at"], name="user_export_idx"
            ),
        ),
    ]
