# Generated by Django 5.0.1 on 2025-10-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("filename", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("total_rows", models.IntegerField(default=0)),
                ("processed_rows", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("duplicate_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_log", models.TextField(blank=True)),
                ("column_mapping", models.TextField(blank=True)),
                ("processing_speed", models.FloatField(blank=True, null=True)),
                ("estimated_completion", models.DateTimeField(blank=True, null=True)),
                ("current_batch", models.IntegerField(default=0)),
                ("total_batches", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "import_jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
